### ISSUE TITLE
[0.5.0] build error!

### ISSUE THREAD

**Issue by c4lliope** [AlexR2D2/duckdbex#59]
For comparison, this uses a cached NIF and finishes quickly:

```elixir
> Mix.install([ {:duckdbex, "~> 0.4.0"} ])
Resolving Hex dependencies...
Resolution completed in 0.085s
New:
  cc_precompiler 0.1.11
  duckdbex 0.4.2
  elixir_make 0.10.0
* Getting duckdbex (Hex package)
* Getting cc_precompiler (Hex package)
* Getting elixir_make (Hex package)
==> elixir_make
Compiling 8 files (.ex)
Generated elixir_make app
==> cc_precompiler
Compiling 3 files (.ex)
Generated cc_precompiler app
==> duckdbex
Compiling 2 files (.ex)
Generated duckdbex app
```

This... is broken in 3 ways:

1. cache miss
2. insufferably long build
3. fails in the end

The full build on my machine? 1345 seconds.
22min 25sec.

```elixir
> Mix.install([ {:duckdbex, "~> 0.5.0"} ])
# ...
g++ -O3 -std=c++11 -DDUCKDB_EXTENSION_CORE_FUNCTIONS_LINKED=1 -DDUCKDB_EXTENSION_PARQUET_LINKED=1  -I"c_src/duckdb/src/include"  -I"c_src/duckdb/third_party/concurrentqueue"  -I"c_src/duckdb/third_party/fast_float"  -I"c_src/duckdb/third_party/fastpforlib"  -I"c_src/duckdb/third_party/fmt/include"  -I"c_src/duckdb/third_party/fsst"  -I"c_src/duckdb/third_party/httplib"  -I"c_src/duckdb/third_party/hyperloglog"  -I"c_src/duckdb/third_party/jaro_winkler"  -I"c_src/duckdb/third_party/jaro_winkler/details"  -I"c_src/duckdb/third_party/libpg_query"  -I"c_src/duckdb/third_party/libpg_query/include"  -I"c_src/duckdb/third_party/lz4"  -I"c_src/duckdb/third_party/brotli/include"  -I"c_src/duckdb/third_party/brotli/common"  -I"c_src/duckdb/third_party/brotli/dec"  -I"c_src/duckdb/third_party/brotli/enc"  -I"c_src/duckdb/third_party/mbedtls/include"  -I"c_src/duckdb/third_party/mbedtls/library"  -I"c_src/duckdb/third_party/miniz"  -I"c_src/duckdb/third_party/pcg"  -I"c_src/duckdb/third_party/pdqsort"  -I"c_src/duckdb/third_party/re2"  -I"c_src/duckdb/third_party/ska_sort"  -I"c_src/duckdb/third_party/skiplist"  -I"c_src/duckdb/third_party/tdigest"  -I"c_src/duckdb/third_party/utf8proc"  -I"c_src/duckdb/third_party/utf8proc/include"  -I"c_src/duckdb/third_party/vergesort"  -I"c_src/duckdb/third_party/yyjson/include"  -I"c_src/duckdb/third_party/zstd/include"  -I"c_src/duckdb/extension/core_functions/include"  -I"c_src/duckdb/extension/parquet/include"  -I"c_src/duckdb/third_party/parquet"  -I"c_src/duckdb/third_party/thrift"  -I"c_src/duckdb/third_party/lz4"  -I"c_src/duckdb/third_party/brotli/include"  -I"c_src/duckdb/third_party/brotli/common"  -I"c_src/duckdb/third_party/brotli/dec"  -I"c_src/duckdb/third_party/brotli/enc"  -I"c_src/duckdb/third_party/snappy"  -I"c_src/duckdb/third_party/mbedtls"  -I"c_src/duckdb/third_party/mbedtls/include"  -I"c_src/duckdb/third_party/zstd/include" -I"/nix/store/kwl0l1c55cgbg8nn9i30ddlcgcszivgb-erlang-29.0.5/lib/erlang/erts-17.0.5/include" -DNDEBUG=1 -fPIC -fvisibility=hidden -c c_src/term.cpp -o /home/calliope/.cache/mix/installs/ex-1.20.3-erl-17.0.5/5saKYSjkU2QTS4PXsn5yYQ/_build/dev/lib/duckdbex/priv/term.o
c_src/term.cpp:28:44: error: ‘uint8_t’ has not been declared
   28 | void get_decimal_major_minor(SIGNED value, uint8_t scale, UNSIGNED& major, UNSIGNED& minor) {
      |                                            ^~~~~~~
c_src/term.cpp:6:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
    5 | #include <vector>
  +++ |+#include <cstdint>
    6 | 
make[1]: *** [Makefile:67: /home/calliope/.cache/mix/installs/ex-1.20.3-erl-17.0.5/5saKYSjkU2QTS4PXsn5yYQ/_build/dev/lib/duckdbex/priv/term.o] Error 1
make[1]: Leaving directory '/home/calliope/.cache/mix/installs/ex-1.20.3-erl-17.0.5/5saKYSjkU2QTS4PXsn5yYQ/deps/duckdbex'
make: *** [Makefile:76: all] Error 2
```

**Comment by rakshans1** [comment]
We hit the same failure in an Alpine/musl production image build using duckdbex 0.5.0 on hexpm/elixir:1.20.3-erlang-28.5.0.5-alpine-3.23.5. Adding `#include <cstdint>` to `c_src/term.cpp` fixes the compile error because the file uses `uint8_t` / `int64_t` directly.\n\nWe are carrying a temporary Dockerfile patch and will remove it once a fixed duckdbex release ships.

**Comment by AlexR2D2** [comment]
Please, check the new 0.5.1 build

**Comment by c4lliope** [comment]
Yes, seems good! I'm so glad you're keeping up on this package!
